services:
  frontend: !override
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev

    ports:
      - 5173:5173

    develop:
      watch:
        - path: ./frontend/src
          target: /app/src
          action: sync
        - path: ./frontend/package.json
          target: /app/package.json
          action: restart
        - path: ./frontend/vite.config.js
          target: /app/vite.config.js
          action: restart

  db: !override
    image: postgres:15-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/data.sql
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
