services:
  quizhub:
    ports: !override
      - "9000:8000"
  quizcore:
    ports: !override
      - "9001:8001"
  frontend:
    ports: !override
      - "9080:8080"
  auth:
    ports: !override
      - "9081:8081"
