"""empty message

Revision ID: efbf1b02f3bf
Revises: aa7bf2bb87ce
Create Date: 2026-07-04 19:27:01.816893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efbf1b02f3bf'
down_revision: Union[str, Sequence[str], None] = 'aa7bf2bb87ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packs', sa.Column('tsv_name', postgresql.TSVECTOR(), sa.Computed("\n            setweight(to_tsvector('english', coalesce(name, '')), 'A')\n            ", persisted=True), nullable=False))
    op.create_index('ix_name_tsv_gin', 'packs', ['tsv_name'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_name_tsv_gin', table_name='packs', postgresql_using='gin')
    op.drop_column('packs', 'tsv_name')
    # ### end Alembic commands ###
