"""empty message

Revision ID: aa7bf2bb87ce
Revises: b8a5d2c4f901
Create Date: 2026-07-04 18:28:42.166831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa7bf2bb87ce'
down_revision: Union[str, Sequence[str], None] = 'b8a5d2c4f901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('published_pack', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('published_pack', sa.Column('tsv_name_desc', postgresql.TSVECTOR(), sa.Computed("\n            setweight(to_tsvector('english', coalesce(description, '')), 'D')\n            ", persisted=True), nullable=False))
    op.create_index('ix_desc_tsv_gin', 'published_pack', ['tsv_name_desc'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_desc_tsv_gin', table_name='published_pack', postgresql_using='gin')
    op.drop_column('published_pack', 'tsv_name_desc')
    op.drop_column('published_pack', 'description')
    # ### end Alembic commands ###
