"""rename column

Revision ID: 99d0383533f5
Revises: efbf1b02f3bf
Create Date: 2026-07-05 16:57:26.168149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99d0383533f5'
down_revision: Union[str, Sequence[str], None] = 'efbf1b02f3bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('published_pack', sa.Column('tsv_desc', postgresql.TSVECTOR(), sa.Computed("\n            setweight(to_tsvector('english', coalesce(description, '')), 'D')\n            ", persisted=True), nullable=False))
    op.drop_index(op.f('ix_desc_tsv_gin'), table_name='published_pack', postgresql_using='gin')
    op.create_index('ix_desc_tsv_gin', 'published_pack', ['tsv_desc'], unique=False, postgresql_using='gin')
    op.drop_column('published_pack', 'tsv_name_desc')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('published_pack', sa.Column('tsv_name_desc', postgresql.TSVECTOR(), sa.Computed('setweight(to_tsvector(\'english\'::regconfig, COALESCE(description, \'\'::text)), \'D\'::"char")', persisted=True), autoincrement=False, nullable=False))
    op.drop_index('ix_desc_tsv_gin', table_name='published_pack', postgresql_using='gin')
    op.create_index(op.f('ix_desc_tsv_gin'), 'published_pack', ['tsv_name_desc'], unique=False, postgresql_using='gin')
    op.drop_column('published_pack', 'tsv_desc')
    # ### end Alembic commands ###
