"""add tsv for course book

Revision ID: cadec56c693e
Revises: 99d0383533f5
Create Date: 2026-07-05 17:24:33.219608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cadec56c693e'
down_revision: Union[str, Sequence[str], None] = '99d0383533f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('published_pack', sa.Column('tsv_course_book', postgresql.TSVECTOR(), sa.Computed("\n            setweight(to_tsvector('english', coalesce(course_book, '')), 'B')\n            ", persisted=True), nullable=False))
    op.create_index('ix_course_book_tsv_gin', 'published_pack', ['tsv_course_book'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_course_book_tsv_gin', table_name='published_pack', postgresql_using='gin')
    op.drop_column('published_pack', 'tsv_course_book')
    # ### end Alembic commands ###
