"""empty message

Revision ID: fe2ebf3f76c2
Revises: 471509bc311b
Create Date: 2026-06-14 12:59:21.327190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe2ebf3f76c2'
down_revision: Union[str, Sequence[str], None] = '471509bc311b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updating_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packs_id'), 'packs', ['id'], unique=False)
    op.create_index(op.f('ix_packs_name'), 'packs', ['name'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('hint', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_index(op.f('ix_cards_pack_id'), 'cards', ['pack_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updating_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_pack_id'), 'comments', ['pack_id'], unique=False)
    op.create_table('forks',
    sa.Column('fork_id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fork_id'], ['packs.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['packs.id'], ),
    sa.PrimaryKeyConstraint('fork_id', 'original_id')
    )
    op.create_index(op.f('ix_forks_fork_id'), 'forks', ['fork_id'], unique=False)
    op.create_index(op.f('ix_forks_original_id'), 'forks', ['original_id'], unique=False)
    op.create_table('published_pack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('subject', sa.String(length=30), nullable=False),
    sa.Column('university', sa.String(length=30), nullable=False),
    sa.Column('professor', sa.String(length=60), nullable=False),
    sa.Column('course_book', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['packs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_published_pack_course_book'), 'published_pack', ['course_book'], unique=False)
    op.create_index(op.f('ix_published_pack_professor'), 'published_pack', ['professor'], unique=False)
    op.create_index(op.f('ix_published_pack_subject'), 'published_pack', ['subject'], unique=False)
    op.create_index(op.f('ix_published_pack_university'), 'published_pack', ['university'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hash', sa.Text(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    op.create_index(op.f('ix_tokens_user_id'), 'tokens', ['user_id'], unique=False)
    op.create_table('card_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_right', sa.Boolean(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_options_id'), 'card_options', ['id'], unique=False)
    op.create_table('replies',
    sa.Column('initial_id', sa.Integer(), nullable=False),
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['initial_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['reply_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('initial_id', 'reply_id')
    )
    op.create_index(op.f('ix_replies_initial_id'), 'replies', ['initial_id'], unique=False)
    op.create_index(op.f('ix_replies_reply_id'), 'replies', ['reply_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replies_reply_id'), table_name='replies')
    op.drop_index(op.f('ix_replies_initial_id'), table_name='replies')
    op.drop_table('replies')
    op.drop_index(op.f('ix_card_options_id'), table_name='card_options')
    op.drop_table('card_options')
    op.drop_index(op.f('ix_tokens_user_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_published_pack_university'), table_name='published_pack')
    op.drop_index(op.f('ix_published_pack_subject'), table_name='published_pack')
    op.drop_index(op.f('ix_published_pack_professor'), table_name='published_pack')
    op.drop_index(op.f('ix_published_pack_course_book'), table_name='published_pack')
    op.drop_table('published_pack')
    op.drop_index(op.f('ix_forks_original_id'), table_name='forks')
    op.drop_index(op.f('ix_forks_fork_id'), table_name='forks')
    op.drop_table('forks')
    op.drop_index(op.f('ix_comments_pack_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_cards_pack_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_packs_name'), table_name='packs')
    op.drop_index(op.f('ix_packs_id'), table_name='packs')
    op.drop_table('packs')
    # ### end Alembic commands ###
