"""empty message

Revision ID: 4ec49b8d931e
Revises: a6c4d5e6f701
Create Date: 2026-07-18 11:50:10.340871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec49b8d931e'
down_revision: Union[str, Sequence[str], None] = 'a6c4d5e6f701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['published_pack.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'pack_id')
    )
    op.create_index(op.f('ix_rating_pack_id'), 'rating', ['pack_id'], unique=False)
    op.create_index(op.f('ix_rating_user_id'), 'rating', ['user_id'], unique=False)
    op.execute("""
        CREATE OR REPLACE FUNCTION calc_rating()
        RETURNS TRIGGER 
        LANGUAGE plpgsql
        AS $body$
        DECLARE 
            target_pack_id INT; 
        BEGIN
            IF (TG_OP = 'DELETE') THEN
                target_pack_id := OLD.pack_id;
            ELSE
                target_pack_id := NEW.pack_id;
            END IF;

            UPDATE published_pack
            SET rating = (SELECT AVG(score) FROM rating WHERE pack_id = target_pack_id)
            WHERE id = target_pack_id;

            RETURN NULL;
        END;
        $body$;
        """)

    op.execute("DROP TRIGGER IF EXISTS trigger_calc_rating ON rating;")

    op.execute("""
       CREATE TRIGGER trigger_calc_rating
        AFTER INSERT OR UPDATE OR DELETE ON rating
        FOR EACH ROW
        EXECUTE FUNCTION calc_rating(); 
               """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER trigger_calc_rating on rating;")
    op.execute("DROP FUNCTION calc_rating()")
    op.drop_index(op.f('ix_rating_user_id'), table_name='rating')
    op.drop_index(op.f('ix_rating_pack_id'), table_name='rating')
    op.drop_table('rating')
    # ### end Alembic commands ###
